FROM node:13.14-alpine as build-deps
WORKDIR /app
COPY package.json ./

RUN npm install
COPY . .
RUN npm run build

# Stage 2 - the production environment
FROM nginx:1.12-alpine
COPY --from=build-deps /app/build /app/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]