version: '3'

services:
  dev:
    build: 
        context: .
        dockerfile: ./Dockerfile.development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src

  prod:
    build: 
        context: .
        dockerfile: ./Dockerfile.production
    ports:
      - '80:80'
    volumes:
      - ./src:/app/src